### ISSUE TITLE
Некорректно работает поиск на сайте (по Пушкину ищется все подряд)

### ISSUE THREAD

**Issue by lup-** [lup-/bmm_shop#19]

**Comment by lup-** [comment]
Поиск не всегда работает корректно, почему-то пишет, что результатов 5 книг, по факту показывает только 4 (данного автора в базе вообще 9 книг, показывает только 4, хотя активность у всех книг проставлена  @AG на самом деле показывает все кроме одной, у которой параметри Доступность=Нет, но только по фамилии автора Гроф, если поиск задан по Станислав Гроф, то в выдаче 4 книжки

![image](https://user-images.githubusercontent.com/2142348/125033052-815d7000-e097-11eb-8f50-2fb1d646c099.png)

**Comment by lup-** [comment]
@KaterinaKozoriz @alexandragolubinova 
посмотрите как работает поиск сейчас, пжл

**Comment by alexandragolubinova** [comment]
прям сильно получче, только ОЧЕНЬ медленно(
на сайте есть раздел про ускорить сайт, может, ускорим?
С уважением,
Александра Голубинова
+7 903 960 98 26


вт, 13 июл. 2021 г. в 17:16, Александр Павлов ***@***.***>:
