### ISSUE TITLE
Логотип в закладку страницы

### ISSUE THREAD

**Issue by KaterinaKozoriz** [lup-/bmm_shop#62]
Поставить логотип БММ закладку страницы

![image](https://user-images.githubusercontent.com/87300633/125290458-01e6cf80-e329-11eb-8bc0-74ff5bbe36d5.png)

**Comment by KaterinaKozoriz** [comment]
https://cloud.mail.ru/public/zdJx/MSGgoHpTp файл favicon не обновлен

**Comment by lup-** [comment]
не, с файлом все норм
это просто упрямый кэш браузера -- скорее всего надо несколько раз нажать на кнопку обновления страницы
![image](https://user-images.githubusercontent.com/2142348/125434305-241b89c4-16dd-4628-920e-3dd8a9d7fa9b.png)
