### ISSUE TITLE
Кириллица в ссылках

### ISSUE THREAD

**Issue by KaterinaKozoriz** [lup-/bmm_shop#70]
Необходимо исключить вероятность создания URL на сайте с кириллическими символами, знаками пунктуации и т.д. Пример: https://s.mail.ru/qFx7/cL93exm5V

Необходимо русские слова переводить в транслитерацию, попутно производить замену пробелов на “-”, а конструкции “--” на единичный символ “-”, все буквы должны быть только в нижнем регистре, все символы типа верхняя одиночная кавычка, скобки фигурные или круглые и другие (напр., https://bmm.ru/publisher/%D0%94%D0%B5'%D0%9B%D0%B8%D0%B1%D1%80%D0%B8/) должны убираться из URL либо заменяться на "-".

Тоже самое касается и страниц фильтрации: https://bmm.ru/latest/filter/cover-is-%D0%BC%D1%8F%D0%B3%D0%BA%D0%B0%D1%8F/apply/

**Comment by lup-** [comment]
Поменял издательства на транслит, а фильтры перенес в параметры запроса, убрал их из чпу
Так норм?

**Comment by KaterinaKozoriz** [comment]
Александр, одной транслитерации недостаточно, я прописывала правила, дублирую их, на всякий случай:
Необходимо исключить вероятность создания URL на сайте с кириллическими символами, знаками пунктуации и т.д. Пример: https://s.mail.ru/qFx7/cL93exm5V

Необходимо русские слова переводить в транслитерацию, попутно производить замену пробелов на “-”, а конструкции “--” на единичный символ “-”, все буквы должны быть только в нижнем регистре, все символы типа верхняя одиночная кавычка, скобки фигурные или круглые и другие (напр., https://bmm.ru/publisher/%D0%94%D0%B5'%D0%9B%D0%B8%D0%B1%D1%80%D0%B8/) должны убираться из URL либо заменяться на "-".

Тоже самое касается и страниц фильтрации: https://bmm.ru/latest/filter/cover-is-%D0%BC%D1%8F%D0%B3%D0%BA%D0%B0%D1%8F/apply/

**Comment by lup-** [comment]
Переделал ссылки в издательствах. Теперь в инфоблок издательств автоматически добавляются элементы, если их нет. Ссылки формируются по адресам этих элементов по шаблону: `/publisher/#ID#_#CODE#/`
#ID# - цифровой код элемента из инфоблока
#CODE# - поле "символьный код"

Для всех старых издательств я проставил символьный код вручную. Для новых он будет генерироваться автоматом -- его можно будет исправить, если что-то не так.
