### ISSUE TITLE
Упорядочить ссылки на текстовые страницы и их взаимодействие. Сделать анкерные ссылки на Странице Правил и-м.  Восстановить названия пунктов меню на текстовых страницах.

### ISSUE THREAD

**Issue by alexandragolubinova** [lup-/bmm_shop#82]
- [x] На странице Правил движение по следующим пунктам:
Как сделать заказ
Доставка
Оплата
Возврат
Политика конфиденциальности

- [x] Из нижнего меню в футере сделать ссылку на страницу Согласия на обработку... (сейчас на Публичную оферту).
а странице Согласия на обработку... поставить заголовок наверх.

- [x] Страницу О нас привести в соответствие с макетом.

- [x] Сделать футер у всех текстовых страниц

**Comment by lup-** [comment]
Пока остались некоторые пустые страницы

**Comment by alexandragolubinova** [comment]
пустые страницы заполню, сделайте, пожалуйста, отдельную для политики
конфиденциальности
С уважением,
Александра Голубинова
+7 903 960 98 26


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Без
вирусов. www.avast.ru
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

чт, 22 июл. 2021 г. в 11:54, Александр Павлов ***@***.***>:
