### ISSUE TITLE
Сплющивание обложек на странице товара

### ISSUE THREAD

**Issue by AnastasiaGryazina** [lup-/bmm_shop#98]
Обложки книг сплющиваются по высоте на странице товара. Если картинок несколько, то при пролистывании и возврате к обложке уже плющится по ширине (пример с Ночь нежна). При просмотре картинок в новой вкладке всё в порядке, т. е. дело не в самих изображениях, а в их отображении на странице (пример с Жизнь и бессмертие — в любви!).
![сплющено по высоте](https://user-images.githubusercontent.com/88135493/127476192-20af84e0-bb66-4f11-b2fc-cd3a669b27fd.PNG)
![сплющено по ширине](https://user-images.githubusercontent.com/88135493/127476217-07474149-e518-4863-988a-312f5c426161.PNG)
![сплющенная](https://user-images.githubusercontent.com/88135493/127476764-f5acda1c-f0d5-42e1-b834-d58854a6dfbe.PNG)
![не сплющенная](https://user-images.githubusercontent.com/88135493/127476781-588e5f1a-9fa5-46d6-89e4-5667f36adf8a.PNG)

**Comment by alexandragolubinova** [comment]
Также необходимо предусмотреть возможность увеличения изображения страниц, сейчас текстовые страницы прочесть невозможно
